sudo: required
dist: trusty
language:
  - minimal
  - cpp

os:
  - linux
  
compiler:
  - gcc

env:
  global:
    - ROS_DISTRO=indigo
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SOURCE_PATH=$(pwd)
    - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'

before_install:

 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
 - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
 - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
 - sudo apt-get update -qq
 - sudo apt-get -y install -f qtbase5-dev qt5-default libqt5svg5-dev
 - sudo apt-get -y install python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
 - source /opt/ros/$ROS_DISTRO/setup.bash
# Prepare rosdep to install dependencies.
 - sudo rosdep init
 - rosdep update

# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - git clone https://github.com/facontidavide/ros_type_introspection.git
  # Create the devel/setup.bash (run catkin_make with an empty workspace) and
  # source it to set the path variables.
  - cd ~/catkin_ws
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
  - catkin_make
  - source devel/setup.bash
  # Add the package under integration to the workspace using a symlink.
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .

before_script:
 - cd ~/catkin_ws
 - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
 
script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin_make

notifications:
  email:
    recipients:
      - davide.faconti@gmail.com
    on_success: change
    on_failure: always
