
name: plotjuggler # you probably want to 'snapcraft register <name>'
version: '1.1.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Just Plot It
description: |
  This is my-snap's description. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  qt-app:    
    source: .
    plugin: qmake cmake
    qt-version: qt5 
    prime:  
      - -usr/share/doc  
      - -usr/include
    after: [desktop-ubuntu-app-platform]
    install: |
      # Create directory to serve as mount point for ubuntu-app-platform
      mkdir $SNAPCRAFT_PART_INSTALL/ubuntu-app-platform
